sudo: false

language: node_js
node_js:
  - "10.14.2"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g yarn

jobs:
  include:
    - stage: flow
      script: yarn run flow-check
    - stage: test
      script: yarn run test
